---
driver:
  name: vagrant
    
provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

transport:
  name: winrm

verifier:
  name: inspec
  format: junit
  output: '%{platform}_%{suite}_inspec.xml'

platforms:
  - name: Windows-2016
    driver:
      box: win2016
    os_type: windows
    shell_type: powershell

suites:
  - name: default
    run_list:
      - recipe[kitchen-ci-windows::kitchen]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      kitchen-ci-windows:
        vagrant-box: []
        jenkins-service: 'TermService'
